export const movieList = [
  {
    id: Math.random(),
    Name: "M3GAN",
    pic: "https://m.media-amazon.com/images/M/MV5BMDk4MTdhYzEtODk3OS00ZDBjLWFhNTQtMDI2ODdjNzQzZTA3XkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_FMjpg_UX1000_.jpg",
    rating: 3,
    genre: "Horror/Sci-Fi/Thriller",
    year: "2022",
  },
  {
    id: Math.random(),
    Name: "PUSS IN BOOTS: THE LAST WISH",
    pic: "https://amc-theatres-res.cloudinary.com/v1672403850/amc-cdn/production/2/movies/66200/66246/Poster/Primary_BoxCover_HD_800_1200.jpg",
    rating: 4,
    genre: "Adventure / Animation / Comedy ",
    year: "2022",
  },
  {
    id: Math.random(),
    Name: "THE MENU",
    pic: "https://m.media-amazon.com/images/M/MV5BMzdjNjI5MmYtODhiNS00NTcyLWEzZmUtYzVmODM5YzExNDE3XkEyXkFqcGdeQXVyMTAyMjQ3NzQ1._V1_.jpg",
    rating: 4,
    genre: "Horror/Mystery/Thriller",
    year: "2022",
  },
  {
    id: Math.random(),
    Name: "MISSING",
    pic: "https://upload.wikimedia.org/wikipedia/en/thumb/5/5d/Missing_poster.jpg/220px-Missing_poster.jpg",
    rating: 4,
    genre: "Mystery/Thriller",
    year: "2023",
  },
  {
    id: Math.random(),
    Name: "AVATAR: THE WAY OF WATER",
    pic: "https://m.media-amazon.com/images/M/MV5BYjhiNjBlODctY2ZiOC00YjVlLWFlNzAtNTVhNzM1YjI1NzMxXkEyXkFqcGdeQXVyMjQxNTE1MDA@._V1_FMjpg_UX1000_.jpg",
    rating: 4,
    genre: " Sci-fi/Adventure",
    year: "2022",
  },
];
